### PR TITLE
Work around bugs in IE and Edge's Range.toString() implementation

### LINKED ISSUE #4: New fromRange implementation can give different outputs in Microsoft Edge and other browsers
Microsoft Edge and Internet Explorer have several bugs related to new lines in the return value of `Range.prototype.toString` which can lead to the [new implementation](https://github.com/tilgovi/dom-anchor-text-position/commit/d0d11e3630588e4f8b2dbddf5cc70d38b2491677) of `fromRange` returning values which are:

1. Different to the start/end positions for the same range returned in Chrome and Firefox
2. Inconsistent with the start/end positions for a given substring in `Node.textContent`. This causes the [dom-anchor-text-quote](https://github.com/tilgovi/dom-anchor-text-quote) library to return incorrect selectors. See https://github.com/tilgovi/dom-anchor-text-quote

Issues that I know of:

1. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110962/
2. Within `<pre>` elements, new lines are reported as `\r\n` instead of `\n` in `Range.toString()` [1]

[1] This prints the same value twice in Chrome/Firefox but different values in Edge:
```html
<html>
<body>
  <pre id="content">
    One
    Two
    Three
  </pre>
  <script>
    var preEl = document.getElementById('content');
    console.log('Text content length', preEl.textContent.length);

    var range = document.createRange();
    range.setStart(preEl, 0);
    range.setEnd(preEl,preEl.childNodes.length);
    console.log('Range content length', range.toString().length);
  </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by robertknight**
Work around the issues with IE and Blink's implementation of Range.toString() described in https://github.com/tilgovi/dom-anchor-text-position/issues/4

The workaround uses a ponyfill for Range.toString() based on a fairly
direct translation of Blink's [Range::toString()](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/Range.cpp?q=range::tostring&sq=package:chromium&l=933) logic.

Tested with the existing tests for this package, plus those from the Hypothesis client. I also compared the output of the native implementation of Range.toString() and the ponyfill on the HTML single-page spec.

The native implementation of Range.toString() is several times faster (60-120ms on https://html.spec.whatwg.org/ vs. ~400ms for the ponyfill), so if we're happy with the approach here, I can follow it up with logic to use the native version if it doesn't have the bugs that IE/Edge's one has.

Fixes #4

### CODE REVIEW

File: test/index_spec.js [hunk 1]
```diff
@@ -131,6 +131,29 @@ describe('textPosition', () => {
       ].join('')
       assert.equal(text, expected)
     })
+
+    it('can describe a range starting at an empty element', () => {
```
Comment (robertknight) [inline test/index_spec.js:135]: These are a couple of extra tests suggested both by the coverage report and the anchoring tests in the Hypothesis client.

File: src/range-to-string.js [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+  } else if (node.nextSibling) {
+    return node.nextSibling
+  }
+  while (node.parentNode) {
+    node = node.parentNode
+    if (node.nextSibling) {
+      return node.nextSibling
+    }
+  }
+  /* istanbul ignore next */
```
Comment (robertknight) [inline src/range-to-string.js:18]: This is pretty hard to hit since it would only apply if the range included the whole `<html>` element.

Comment (tilgovi) [reply src/range-to-string.js:18]: Alternatively, I think it could be written like this:

```js
if (!skipChildren && node.firstChild) {
  return node.firstChild
}

do {
  if (node.nextSibling) {
    return node.nextSibling
  }
  node = node.parentNode
} while(node)

return node
```

File: src/range-to-string.js [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+  return null
+}
+
+function firstNode(range) {
+  if (range.startContainer.nodeType === Node.ELEMENT_NODE) {
+    const node = range.startContainer.childNodes[range.startOffset]
+    return node || range.startContainer
```
Comment (tilgovi) [inline src/range-to-string.js]: Should this be `node || nextNode(range.startContainer)`? If the offset is past all the children, that would logically place the contents of the range after the start container, to me. Of course, this is an exceptional case that I'm not even sure is possible with browser-supplied range support. Your thoughts? I'm not committed either way.

**Review by tilgovi — COMMENTED** [review]
Looks really great! Thank you. Let me know your thoughts on my few comments, and then I'll be happy to merge.

File: src/range-to-string.js (hunk 3 above)
Comment (robertknight) [reply src/range-to-string.js]: > If the offset is past all the children, that would logically place the contents of the range after the start container, to me. 

The most obvious case for this is when the range starts at an empty element, ie. `range.startContainer` is an element with no children (perhaps a `<br>` or empty paragraph or span) and `range.startOffset` is zero. I haven't verified whether it is possible to create such a range manually in any browser, but nothing in the spec forbids it either.

Returning `range.startContainer` here guarantees that the node returned by `firstNode(range)` <= `range.endContainer` (in tree order), which I think is a useful invariant to have.

File: src/range-to-string.js (hunk 2 above)
Comment (robertknight) [reply src/range-to-string.js:18]: That looks neater to me. I'll update this function.

File: src/range-to-string.js (hunk 3 above)
Comment (tilgovi) [reply src/range-to-string.js]: The invariant `firstNode(range) <= firstNodeAfter(range)` would still hold, which is the important condition for ensuring the `forEachNodeInRange` loop exits.

In practice, I think I've come across many times when browsers generate ranges with an offset that is at the end of the `startContainer`. I'm worried that in this scenario, we'll then count text that might have been part of a previous child of the `startContainer`. I cannot see any harm in using `|| nextNode(range.startContainer, true)`, can you?

In the case where this would result in something that comes after the end container, the range is collapsed.

Actually, thinking about this just now makes me realize that it's possible to create a range with a start that is past its end, and `collapsed` will be `true`. We should maybe check for `range.collapsed` before we call `forEachNodeInRange` and short circuit the whole operation, returning the empty string.

What do you think?

Comment (robertknight) [reply src/range-to-string.js]: > In practice, I think I've come across many times when browsers generate ranges with an
> offset that is at the end of the startContainer

Ah, I see your point. You're right, this will return the wrong value if the range starts at the end of a non-empty Element. I've made the change suggested and added a test case.

> Actually, thinking about this just now makes me realize that it's possible to create a range with a start that is past its end, and collapsed will be true

When calling `range.setStart` with a point past the current end, the end is moved to the new start position. Likewise, calling `range.setEnd` with a point before the current start will move the start to the new end position.

I have added a test case for this.

**Comment by tilgovi** [comment]
Excellent! Thanks, Robert.
